import type { Metadata } from "next";
import { Inter,  Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/SharedCompo/Navbar";
import Footer from "@/Components/SharedCompo/Footer";
import WorkoutProvider from "@/context/WorkoutProvider";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: "variable",
});

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: "variable",
});

export const metadata: Metadata = {
  title: "Fitness Log ",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme = "light"
      className={`${inter.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <WorkoutProvider>
          <Navbar></Navbar>
            {children}
            <div className="border-b"></div>
          <Footer></Footer>
        </WorkoutProvider>
      </body>

    </html>
  );
}
